WhatsApp
stepva/chatalysis pull request #99
Opened 2023-03-07 16:26 UTC by miskfi

Implemented WhatsApp processing. We need to create a new template @stepva.

Closes #65

2023-03-14 19:23 UTC, miskfi commented
Added the template, ready to merge.

2025-04-21 17:55 UTC, stepva requested changes
:(

2025-04-21 17:55 UTC, stepva commented on chatalysis/sources/whatsapp.py
> +        self._regex_whatsapp = regex.compile(r"([0-9]*)/([0-9]*)/([0-9]*), ([0-9]*):[0-9]* - ([^:]*):(.*)")
i'm afraid whatsapp will be tricky. I just exported my data for one chat from whatsapp and this regex does not fit. My one message looks for example like this:
```[13.06.2023, 18:08:08] ~ YSL: Zdravime…👋```

while this regex for your case expects timestamp in different format, based on line 63 MM/DD/YYYY and not DD.MM.YYYY

who THE FUCK in meta decided to make exports localized???

2025-09-14 22:18 UTC, miskfi commented on chatalysis/sources/whatsapp.py
> +        self._regex_whatsapp = regex.compile(r"([0-9]*)/([0-9]*)/([0-9]*), ([0-9]*):[0-9]* - ([^:]*):(.*)")
I had some spare time so I decided to solve this. Right now, my code can handle `-` and `~` as delimiters between the date and name/message, optional opening and closing `[]` parentheses and hopefully all possible datetime formats with the `dateparser library`.

It's very likely that there are other formats, delimiters, or whatever that I haven't covered but I guess this will have to do for now.

2025-12-26 12:42 UTC, stepva approved these changes
merry christmas

2025-12-26 12:50 UTC, merged